package org.example.parser;

public enum LogoTokenType {
    //PROCEDURE KEYWORDS
    TO, END,
    PROCEDURE_KEYWORD,
    //LOOPS
    LOOP_KEYWORD,
    CONDITION_KEYWORD,
    //COMMANDS
    POSITION_COMMAND,
    TURTLE_QUERY,
    PEN_COMMAND,
    PEN_QUERY,
    DRAWING_COMMAND,
    WINDOW_COMMAND,
    WINDOW_QUERY,
    MATH_COMMAND,
    LOGIC_COMMAND,
    LIST_COMMAND,
    OUTPUT_COMMAND,
    CONTROL_COMMAND,
    PROCEDURE_COMMAND,
    VARIABLE_COMMAND,
    PREDICATE_COMMAND,
    RECEIVER_COMMAND,
    // USER PROCEDURES
    IDENTIFIER,
    DEFINITION_KEYWORD,
    //VARIABLES
    VARIABLE,
    // LITERALS
    NUMBER,
    STRING,
    COMMENT,
    SYMBOL,
    OPERATOR,
    //SYMBOLS
    NEWLINE,
    // FALLBACK
    UNKNOWN
}
